---
title: "Figure4_Map of MPA and fishing locations"
author: "Yutian Fang"
date: '2022-09-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Clean Environment

rm(list = ls())

### Load packages

library(tidyverse)
library(sf)
library(rnaturalearth)
```

```{r}
### Load in data

SWFSC_trip_orig <- readRDS ("original data/SWFSC_1990_2017_set_net_observer_trips.Rds")

usa <- rnaturalearth::ne_states(country = "United States of America", returnclass = "sf")

mexico <- rnaturalearth::ne_countries(country="Mexico", returnclass = "sf")

wc_blocks <- wcfish::blocks

mpas <- wcfish::mpas_ca %>%
  sf::st_as_sf() %>%
  filter(type != "SMP")
```

```{r}

### Build up data_xy
data_xy <- SWFSC_trip_orig %>%
  filter(!is.na(haul_lat_dd) & !is.na(haul_long_dd)) %>%
  separate("date_haul1", c("year", "month", "day"), sep = "-") %>%
  filter(year >= 2000)
```

```{r}
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.text.y = element_text(angle = 90, hjust = 0.5),
                   axis.title=element_blank(),
                   legend.text=element_text(size=7),
                   legend.title=element_text(size=8),
                   plot.tag=element_text(size=8),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.key.size = unit(0.4, "cm"),
                   legend.key = element_rect(fill = NA), 
                   legend.background = element_rect(fill=alpha('blue', 0)))

 ggplot() +
  # Plot blocks
  geom_sf(data=wc_blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot points
  geom_point(data=data_xy, mapping=aes(x=haul_long_dd, y=haul_lat_dd), 
             pch=21, size=0.8, alpha=0.3, color="grey30") +
  # Plot MPAs
  geom_sf(data=mpas, fill="red", color=NA, alpha=0.6) +
  # Labels
  labs(x="", y="") +
  # Axes
  # scale_y_continuous(breaks=32:42) +
  # Crop
  coord_sf(xlim = c(-120.5, -117), ylim = c(32.3, 34.5)) +
  # Theme
  theme_bw() + my_theme

```

```{r}
### Read in data

distance_mpa <- read.csv("processed data/distance_MPA.csv")

distance_bycatch <- read.csv("processed data/distance_bycatch.csv")


mpa_filter <- mpas %>%
  filter(lat_dd <= 35.5)

mpa_filter_ID <- mpa_filter %>%
  mutate(ID = seq.int(nrow(mpa_filter))) %>%
  select(name, ID) %>%
  st_drop_geometry()

distance_mpa_name <- merge(distance_mpa, mpa_filter_ID, by = "ID") %>%
  select(set_id, name)

distance_bycatch_name <- merge(distance_bycatch, distance_mpa_name, by = "set_id") %>%
  rename(mpa_name = name)

```

```{r}
Figure_4 <- ggplot() +
  # Plot blocks
  geom_sf(data=wc_blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot points
  geom_point(data=distance_bycatch_name , mapping=aes(x=haul_long_dd, y=haul_lat_dd, color=mpa_name), 
             pch=21, size=0.8, alpha=0.3) +
  # Plot MPAs
  geom_sf(data=mpas, mapping=aes(fill=name), color="grey30", lwd=0.1) +
  # Labels
  labs(x="", y="") +
  # Axes
  # scale_y_continuous(breaks=32:42) +
  # Crop
  coord_sf(xlim = c(-120.5, -117), ylim = c(32.3, 34.5)) +
  # Theme
  theme_bw() + my_theme +
  theme(legend.position = "none")

Figure_4
```

```{r}
### Export distance_bycatch_name

write.table(distance_bycatch_name, file = "processed data/distance_bycatch_name.csv", row.names = F, sep = ",")
```

```{r}
### save the figure from above
ggsave(Figure_4, filename= file.path("Figures", "Fig4_map_MPA_fishing_locations.png"),
       width = 7, height = 4, units = "in", dpi = 600)
```

