---
title: "Figures_distance_state_water"
author: "Yutian Fang"
date: '2022-09-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Clean environment

rm(list = ls())

### Load in packages

library(tidyverse)
library(sf)
library(rnaturalearth)

```

```{r}
### Read in data

## Read in spatial data
boundary <- read_sf("original data/geographical_data/StateWaterJurisdiction/MAN_CA_StateWaterLine.shp") %>%
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0") %>%
  filter(STATE == "California")

usa <- rnaturalearth::ne_states(country = "United States of America", returnclass = "sf")

mexico <- rnaturalearth::ne_countries(country="Mexico", returnclass = "sf")

blocks <- wcfish::blocks

wc_port <- wcfish::ports


## Read in attribute data
distance_bycatch_ratio_block <- read.csv("processed data/distance_bycatch_ratio_block.csv")

distance_BPUE_block <- read.csv("processed data/distance_BPUE_block.csv")

SWFSC_trip_orig <- readRDS("original data/SWFSC_1990_2017_set_net_observer_trips.Rds")

```

```{r}
### Make Map of set gillnet fishing locations (2000 - 2017) and state water boundary (with all 1268 observations)

gillnet_coord_exp <- read.csv("processed data/gillnet_coord_exp.csv")

wc_port_ca <- wc_port %>%
  filter(port %in% c("Oceanside", "San Diego", "Mission Bay", "San Pedro", "Newport Beach", "Los Angeles", "Dana Point", "Long Beach", "Ventura", "Oxnard", "Santa Barbara"))

### Create my theme
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.text.y = element_text(angle = 90, hjust = 0.5),
                   axis.title=element_blank(),
                   legend.text=element_text(size=7),
                   legend.title=element_text(size=8),
                   plot.tag=element_text(size=8),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.key.size = unit(0.4, "cm"),
                   legend.key = element_rect(fill = NA), 
                   legend.background = element_rect(fill=alpha('blue', 0)))

Figure <- ggplot() +
  # Plot blocks
  geom_sf(data=blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot points
  geom_point(data=gillnet_coord_exp, mapping=aes(x=haul_long_dd, y=haul_lat_dd), 
             color = "grey30", pch=21, size=0.8, alpha=0.3) +
  # Plot State Water Boundary
  geom_sf(data = boundary, color = "red", fill = NA, lwd = 0.2, linetype = "dashed") +
  # Plot Ports
  geom_point(data = wc_port_ca,
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "red") +
  #Add label to ports
  ggrepel::geom_text_repel(wc_port_ca, mapping=aes(x = long_dd, y = lat_dd, label = port), size = 3, show.legend = F) +
  # Labels
  labs(x="", y="") +
  # Axes
  # scale_y_continuous(breaks=32:42) +
  # Crop
  coord_sf(xlim = c(-120.5, -117), ylim = c(32.3, 34.5)) +
  # Theme
  theme_bw() + my_theme +
  theme(legend.position = "none")

Figure


### Export figure above

ggsave(Figure, filename= file.path("Figures", "map_boundary_fishing_locations_2006-2017.png"),
       width = 5, height = 4, units = "in", dpi = 600)

```



```{r}

### Make map of set gillnet fishing locations (2000-2017) and state water boundary
wc_port_ca <- wc_port %>%
  filter(port %in% c("Oceanside", "San Diego", "Mission Bay", "San Pedro", "Newport Beach", "Los Angeles", "Dana Point", "Long Beach", "Ventura", "Oxnard", "Santa Barbara"))

### Create my theme
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.text.y = element_text(angle = 90, hjust = 0.5),
                   axis.title=element_blank(),
                   legend.text=element_text(size=7),
                   legend.title=element_text(size=8),
                   plot.tag=element_text(size=8),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.key.size = unit(0.4, "cm"),
                   legend.key = element_rect(fill = NA), 
                   legend.background = element_rect(fill=alpha('blue', 0)))

### Create map of fishing locations and state water boundary
Figure_6 <- ggplot() +
  # Plot blocks
  geom_sf(data=blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot points
  geom_point(data=distance_bycatch_ratio_block , mapping=aes(x=haul_long_dd, y=haul_lat_dd, color=region), 
             pch=21, size=0.8, alpha=0.3) +
  # Plot State Water Boundary
  geom_sf(data = boundary, color = "grey50", fill = NA, lwd = 0.2, linetype = "dashed") +
  # Plot Ports
  geom_point(data = wc_port_ca,
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "grey30") +
  #Add label to ports
  ggrepel::geom_text_repel(wc_port_ca, mapping=aes(x = long_dd, y = lat_dd, label = port), size = 1.5, show.legend = F) +
  # Labels
  labs(x="", y="") +
  # Axes
  # scale_y_continuous(breaks=32:42) +
  # Crop
  coord_sf(xlim = c(-120.5, -117), ylim = c(32.3, 34.5)) +
  # Theme
  theme_bw() + my_theme +
  theme(legend.position = "none")

Figure_6
```


```{r}
### Save the figure of the map with state water boundary 
ggsave(Figure_6, filename= file.path("Figures", "Fig6_map_boundary_fishing_locations.png"),
       width = 5, height = 4, units = "in", dpi = 600)
```



```{r}
### Make scatter plot of bycatch ratio (overall, filter out outliers)
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_bycatch_ratio_block %>% filter(distance_km <= 10) %>% filter(!is.na(region)) %>% filter(region != "Santa Cruz Island"), aes(x=distance_km, y=bycatch_ratio)) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  #scale_y_continuous(trans = "log10") +
  geom_smooth(method = "gam", fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch Ratio") +
  # Theme
  theme_bw() + my_theme

```


```{r}
### Make scatter plots of bycatch ratio (by hotspots)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_bycatch_ratio_block %>%filter(!is.na(region)) %>% filter(bycatch_ratio != 0), aes(x=distance_km, y=bycatch_ratio)) +
  facet_wrap(~region, ncol=4, scales="free",
             labeller = labeller(region = label_wrap_gen(width = 16))) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  geom_smooth(method = "lm", formula = log(y)~x, fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch Ratio") +
  # Theme
  theme_bw() + my_theme
```

```{r}
### Create boxplot for bycatch ratio and distance category

distance_bycatch_ratio_block_distcatg <- distance_bycatch_ratio_block %>%
   mutate(dist_catg = cut(distance_km, breaks = seq(0, 75,0.5), 
                         label = seq(0, 74.5, 0.5), right = F) %>% as.character()) %>%
  filter(!is.na(region)) %>%
  filter(region != "Santa Cruz Island")

ggplot()+
  geom_boxplot(data = distance_bycatch_ratio_block_distcatg, aes(x = dist_catg, y = bycatch_ratio), fill = "grey60") +
  scale_y_continuous(trans = "log10") +
  labs(x = "Distance category (km)", y = "Bycatch ratio") +
  theme_bw() + my_theme
```

```{r}
### Create boxplot figure with BPUE and mesh size category
base_theme <- theme(axis.text=element_text(size=6),
                    axis.title=element_text(size=8),
                    legend.text=element_text(size=6),
                    legend.title=element_text(size=8),
                    strip.text=element_text(size=8),
                    # Gridlines
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"))
ggplot()+
  geom_boxplot(data = distance_BPUE_block %>% mutate(net_mesh_size_in = as.character(net_mesh_size_in)), aes(x = net_mesh_size_in, y = BPUE), fill = "grey60") +
  scale_y_continuous(trans = "log10") +
  labs(x = "Mesh size category", y = "Bycatch per unit effort") +
  theme_bw() + base_theme
```

```{r}
### Create boxplot figure with CPUE and mesh size category
ggplot()+
  geom_boxplot(data = distance_BPUE_block %>% mutate(net_mesh_size_in = as.character(net_mesh_size_in)), aes(x = net_mesh_size_in, y = CPUE), fill = "grey60") +
  scale_y_continuous(trans = "log10") +
  labs(x = "Mesh size category", y = "Capture per unit effort") +
  theme_bw() + base_theme
```

```{r}
### Create boxplot figure between BPUE and distance category to state water boundary

ggplot()+
  geom_boxplot(data = distance_BPUE_block %>% filter(distance_km <= 10) %>% mutate(dist_catg = as.character(dist_catg)), aes(x = dist_catg, y = BPUE), fill = "grey60") +
  scale_y_continuous(trans = "log10") +
  labs(x = "Distance category (km)", y = "Bycatch per unit effort") +
  theme_bw() + base_theme
```

```{r}

### Create boxplot figure between CPUE and distance category to state water boundary

ggplot()+
  geom_boxplot(data = distance_BPUE_block %>% filter(distance_km <= 10) %>% mutate(dist_catg = as.character(dist_catg)), aes(x = dist_catg, y = CPUE), fill = "grey60") +
  scale_y_continuous(trans = "log10") +
  labs(x = "Distance category (km)", y = "Capture per unit effort") +
  theme_bw() + base_theme

```
```{r}

### Make scatter plot of BPUE and distance to state water boundary (overall, filter out outliers)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_BPUE_block %>% filter(distance_km <= 10) %>% filter(!is.na(region)) %>% filter(region != "Santa Cruz Island"), aes(x=distance_km, y= BPUE)) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  # Make y_scale in log10
  scale_y_continuous(trans = "log10") +
  # Fit a gam line to the graph
  geom_smooth(method = "gam", fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch per unit effort (in log10)") +
  # Theme
  theme_bw() + my_theme
```

```{r}
### Make scatter plots of BPUE and distance to state water boundary (by hotspots)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_BPUE_block %>%filter(!is.na(region)) %>% filter(region != "Santa Cruz Island"), aes(x=distance_km, y=BPUE)) +
  facet_wrap(~region, ncol=4, scales="free",
             labeller = labeller(region = label_wrap_gen(width = 16))) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  scale_y_continuous(trans = "log10") +
  geom_smooth(method = "gam", fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch per unit effort (in log10)") +
  # Theme
  theme_bw() + my_theme
```

```{r}
### Make scatter plot of CPUE and distance to state water boundary (overall, filter out outliers)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_BPUE_block %>% filter(distance_km <= 10) %>% filter(!is.na(region)) %>% filter(region != "Santa Cruz Island"), aes(x=distance_km, y= CPUE)) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  # Make y_scale in log10
  scale_y_continuous(trans = "log10") +
  # Fit a gam line to the graph
  geom_smooth(method = "gam", fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Capture per unit effort (in log10)") +
  # Theme
  theme_bw() + my_theme
```

```{r}
### Make scatter plot of CPUE and distance to state water boundary (hotspots, filter out outliers)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))


ggplot(distance_BPUE_block %>%filter(!is.na(region)) %>% filter(region != "Santa Cruz Island"), aes(x=distance_km, y=CPUE)) +
  facet_wrap(~region, ncol=4, scales="free",
             labeller = labeller(region = label_wrap_gen(width = 16))) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  scale_y_continuous(trans = "log10") +
  geom_smooth(method = "gam", fill="grey40", color="black") +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch per unit effort (in log10)") +
  # Theme
  theme_bw() + my_theme

```

```{r}
### Make BPUE map

### set up theme ###

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.text.y = element_text(angle = 90, hjust = 0.5),
                   axis.title=element_blank(),
                   legend.text=element_text(size=7),
                   legend.title=element_text(size=8),
                   plot.tag=element_text(size=8),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.key.size = unit(0.4, "cm"),
                   legend.key = element_rect(fill = NA), 
                   legend.background = element_rect(fill=alpha('blue', 0)))

ggplot() +
  # Plot blocks
  geom_sf(data=blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot points
  geom_point(data= distance_BPUE_block %>% filter(BPUE != 0), mapping=aes(x=haul_long_dd, y=haul_lat_dd, color = BPUE),
             pch=20, size=0.8, alpha=0.3) +
  # Plot Ports
 geom_point(data = wc_port_ca,
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "grey30") +
  #Add label to ports
  ggrepel::geom_text_repel(wc_port_ca, mapping=aes(x = long_dd, y = lat_dd, label = port), size = 1.5, show.legend = F) +
  # Labels
  labs(x="", y="") +
    # Legend
  scale_color_gradientn(name="Bycatch per unit effort", 
                       colors=RColorBrewer::brewer.pal(9, "YlOrRd"), 
                       trans="log10") +
  guides(fill = guide_colorbar(ticks.colour = "black", frame.colour = "black")) +
  # Crop
  coord_sf(xlim = c(-120.5, -117), ylim = c(32.3, 34.5)) +
  # Theme
  theme_bw() + my_theme



```

```{r}

### Just for Santa Barbara?

ggplot() +
  # Plot blocks
  geom_sf(data=blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot State water boundary
  geom_sf(data = boundary, color = "blue", fill = NA, lwd = 0.3) +
  # Plot points
  geom_point(data= distance_BPUE_block %>% filter(BPUE != 0) %>% filter(region == "Santa Barbara"),
             mapping=aes(x=haul_long_dd, y=haul_lat_dd, color = BPUE),
             pch=20, size=2, alpha = 0.5) +
  # Plot Ports
 geom_point(data = wc_port_ca %>% filter(port %in% c("Santa Barbara", "Ventura", "Oxnard")),
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "grey30") +
  #Add label to ports
  ggrepel::geom_text_repel(wc_port_ca %>% filter(port %in% c("Santa Barbara", "Ventura", "Oxnard")), mapping=aes(x = long_dd, y = lat_dd, label = port), size = 1.5, show.legend = F) +
  # Labels
  labs(x="", y="") +
    # Legend
  scale_color_gradientn(name="Bycatch per unit effort", 
                       colors=RColorBrewer::brewer.pal(9, "RdYlGn") %>% rev(), 
                       trans="log10") +
  guides(fill = guide_colorbar(ticks.colour = "black", frame.colour = "black")) +
  # Crop
  coord_sf(xlim = c(-120, -119), ylim = c(34, 34.5)) +
  # Theme
  theme_bw() + my_theme

```

```{r}
### and for San Diego?

ggplot() +
  # Plot blocks
  geom_sf(data=blocks, color="grey60", fill=NA, lwd=0.1) +
  # Plot land
  geom_sf(data=mexico, fill="grey80", color="white", lwd=0.3) +
  geom_sf(data=usa, fill="grey80", color="white", lwd=0.3) +
  # Plot State water boundary
  geom_sf(data = boundary, color = "blue", fill = NA, lwd = 0.3) +
  # Plot points
  geom_point(data= distance_BPUE_block %>% filter(BPUE != 0) %>% filter(region == "San Diego"),
             mapping=aes(x=haul_long_dd, y=haul_lat_dd, color = BPUE),
             pch=20, size=2, alpha = 0.5) +
  # Plot Ports
 geom_point(data = wc_port_ca %>% filter(port == "San Diego"),
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "grey30") +
  #Add label to ports
  ggrepel::geom_text_repel(wc_port_ca %>% filter(port == "San Diego"), mapping=aes(x = long_dd, y = lat_dd, label = port), size = 1.5, show.legend = F) +
  # Labels
  labs(x="", y="") +
    # Legend
  scale_color_gradientn(name="Bycatch per unit effort", 
                       colors=RColorBrewer::brewer.pal(9, "RdYlGn") %>% rev(), 
                       trans="log10") +
  guides(fill = guide_colorbar(ticks.colour = "black", frame.colour = "black")) +
  # Crop
  coord_sf(xlim = c(-117.5, -117), ylim = c(32.5, 33)) +
  # Theme
  theme_bw() + my_theme
```


