---
title: "Figure 8_Distance_sw_fishing_efforts"
output: html_document
date: "2022-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Clean working environment

rm(list = ls())

### Load in package

library(tidyverse)
```


```{r}
### Read in data

distance_state_water <- read.csv("processed data/distance_bycatch_state_water.csv") %>%
  select(set_id, distance)

SWFSC_trip_orig <- readRDS ("original data/SWFSC_1990_2017_set_net_observer_trips.Rds")
```

```{r}
### Format data

SWFSC_trip_soak_hr <- SWFSC_trip_orig %>%
  select(set_id, soak_hr)

distance_soak_hr <- merge(distance_state_water, SWFSC_trip_soak_hr, by = "set_id") %>%
  mutate(distance_km = distance/1000) %>%
  mutate(dist_catg = cut(distance_km, breaks = seq(0, 75,0.5), 
                         label = seq(0, 74.5, 0.5), right = F) %>% as.character() %>% as.numeric()) %>%
  group_by(dist_catg) %>%
  summarize(soak_hr_total = sum(soak_hr, na.rm = T))
```

```{r}
#### Make plot ####

### Set up theme
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   legend.text=element_text(size=6),
                   legend.title=element_text(size=8),
                   strip.text=element_text(size=8),
                   plot.title=element_text(size=10),
                   # Gridlines
                   panel.border = element_blank(),
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))

### Plot data

Figure_8 <-  ggplot(distance_soak_hr, aes(x=dist_catg, y=soak_hr_total)) +
  geom_bar(stat="identity") +
  # Labels
  labs(x="Distance from state water boundary (km)", y="Soaking hours\n(from 2000-2017, cumlatively)") +
  scale_x_continuous(breaks=seq(0, 73, 5)) +
  # Theme
  theme_bw() + my_theme +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

Figure_8

```


```{r}
### save the plot above
ggsave(Figure_8, filename= file.path("Figures", "Fig8_bin_fishing_efforts.png"),
       width = 7, height = 4, units = "in", dpi = 600)
```

