---
title: "Figure 3_Map of Median fishing efforts"
output: html_document
date: "2022-09-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Clean environment

rm(list = ls())


### Load in package

library(tidyverse)
library(sf)
library(rnaturalearth)
library(tigris)
```

```{r}
### Read in data

SWFSC_observer_orig <- readRDS("original data/SWFSC_set_net_observer_data.Rds")
SWFSC_trip_orig <- readRDS ("original data/SWFSC_1990_2017_set_net_observer_trips.Rds")
SWFSC_trip_block <- read.csv("processed data/gillnet_coord_all.csv")

### Read in spatial data

usa <- rnaturalearth::ne_states(country = "United States of America", returnclass = "sf")

mexico <- rnaturalearth::ne_countries(country="Mexico", returnclass = "sf")

wc_port <- wcfish::ports

wc_blocks <- wcfish::blocks

```

```{r}
### Build Bycatch Data

observer_bycatch_ratio <- SWFSC_observer_orig %>%
  select(set_id, comm_name, n_caught, n_kept, condition_code) %>%
  mutate(n_caught = ifelse(!is.na(condition_code), 1, n_caught)) %>%
  mutate(n_kept = ifelse(is.na(n_kept), 0 , n_kept)) %>%
  filter(!is.na(n_caught)) %>%
  mutate(bycatch = n_caught - n_kept) %>%
  group_by(set_id) %>%
  summarize(bycatch = sum(bycatch), n_kept = sum(n_kept)) %>%
  filter(n_kept != 0) %>%
  mutate(bycatch_ratio = bycatch/n_kept) %>%
  mutate_if(is.numeric, round, digits = 4) %>%
  select(set_id, bycatch_ratio)

  

SWFSC_set_bycatch <- left_join(SWFSC_trip_block, observer_bycatch_ratio, by = "set_id") %>%
  filter(!is.na(bycatch_ratio)) %>%
  group_by(block_id) %>%
  summarize(median_bycatch_ratio = median(bycatch_ratio))



### Format spatial data

wc_port_ca <- wc_port %>%
  filter(port %in% c("Oceanside", "San Diego", "Mission Bay", "San Pedro", "Newport Beach", "Los Angeles", "Dana Point", "Long Beach", "Ventura", "Oxnard", "Santa Barbara", "Avila/Port San Luis", "Morro Bay", "Moss Landing", "Santa Cruz", "Monterey"))

fishing_block_selected <- wc_blocks %>%
  filter(block_state == "California")

### Merge bycatch and spatial dataset
SWFSC_set_bycatch_block <- merge(fishing_block_selected, SWFSC_set_bycatch, by = "block_id")
```


```{r}
#### Make plot ####

### Set up basic theme

base_theme <- theme(axis.text=element_text(size=7),
                    axis.title=element_blank(),
                    legend.text=element_text(size=8),
                    legend.title=element_text(size=9),
                    plot.title=element_blank(),
                    # Gridlines
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"),
                    axis.text.y = element_text(angle = 90, hjust = 0.5))

### Make plot

Figure_3 <- ggplot() +
  geom_sf(data = SWFSC_set_bycatch_block, mapping = aes(fill = median_bycatch_ratio), color = "grey60", lwd = 0.1) +
  geom_sf(data = usa, fill = "grey85", col = "white", size = 0.2) +
  geom_sf(data=mexico, fill="grey85", col="white", size=0.2) +
  geom_point(data = wc_port_ca,
             mapping = aes(x = long_dd, y = lat_dd), pch = 8, color = "grey30") +
  ggrepel::geom_text_repel(wc_port_ca, mapping=aes(x = long_dd, y = lat_dd, label = port), size = 1.5, show.legend = F) +
  scale_fill_gradientn(name = "Median Bycatch Ratio", colors = RColorBrewer::brewer.pal(9, "YlOrRd")) +
  coord_sf(xlim = c(-122.5, -117), ylim = c(32.3, 37))+
  theme_bw() + base_theme

Figure_3
```

```{r}
### save figure above

ggsave(Figure_3, filename= file.path("Figures", "Fig3_map_median_bycatch_ratio.png"),
       width = 7, height = 4, units = "in", dpi = 600)
```

