---
title: "sw_distance_bycatch_ratio_modeling"
author: "Yutian Fang"
date: '2022-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Clean environment

rm(list = ls())

### Load in packages

library(tidyverse)
library(quantreg)
library(sf)

```

```{r}
### Read in data

# Read in fishing location
fishing_locations <- read.csv("processed data/gillnet_coord_exp.csv") %>%
  select(set_id, haul_lat_dd, haul_long_dd)

# distance to state water boundary 
distance_sw <- read.csv("processed data/distance_bycatch_state_water.csv") %>%
  select(-lon, -lat, -ID)

# original observer data from SWFSC
SWFSC_observer_orig <- readRDS("original data/SWFSC_set_net_observer_data.Rds")

# block data
blocks <- wcfish::blocks



```

```{r}
### Build up observer data to calculate bycatch ratio

SWFSC_bycatch_set <- SWFSC_observer_orig %>%
  # For protected species, they won't write down n_caught instead of assigning condition_code, each condition_code corresponding to 1 bycatch
  mutate(n_caught = ifelse(!is.na(condition_code), 1, n_caught)) %>%
  # Then filter out NA n_caught for unknown species 
  filter(!is.na(n_caught)) %>%
  # For protected species, they won't write down n_kept but fishermen won't kept protected species, so n_kept will actually be 0
  mutate(n_kept = ifelse(is.na(n_kept), 0, n_kept)) %>%
  # Now ready to calculate bycatch, defined as n_caught - n_kept
  mutate(bycatch = n_caught - n_kept) %>%
  group_by(set_id) %>%
  # bycatch per set and capture per set defined as the sum of n_caught and n_kept for each set
  summarize(bycatch_set = sum(bycatch), capture_set = sum(n_kept))
```


```{r}

### Merge the bycatch data with the distance to state water boundary data

distance_sw_bycatch <- merge(distance_sw, SWFSC_bycatch_set, by = "set_id") %>%
  mutate(distance_km = distance/1000) %>%
  filter(capture_set != 0) %>%
  mutate(bycatch_ratio = bycatch_set/capture_set) %>%
  # filter out outliers
  filter(bycatch_ratio <= 100)

### Merge with fishing locations (haul_long_dd and haul_lat_dd)
distance_sw_bycatch_location <- merge(distance_sw_bycatch, fishing_locations, by = "set_id") %>%
  # rearrange the columns
  select(set_id, bycatch_set, capture_set, bycatch_ratio, distance, distance_km, haul_long_dd, haul_lat_dd)
```

```{r}
### convert to sf and sp

distance_sw_bycatch_location_sp <- distance_sw_bycatch_location %>%
  st_as_sf(coords = c("haul_long_dd", "haul_lat_dd"), crs = st_crs(blocks), remove = F ) %>%
  as_Spatial()

blocks_sp <- blocks %>% 
  as_Spatial()

### Intersect with blocks 

distance_bycatch_block_ids <- sp::over(distance_sw_bycatch_location_sp, blocks_sp) %>%
  pull(block_id)

### Add block_id to distance_bycatch_sw

distance_bycatch_ratio_block <- distance_sw_bycatch_location %>%
  mutate(block_id = distance_bycatch_block_ids) %>%
  filter(!is.na(block_id)) %>%
  mutate(block_id = as.character(block_id)) %>%
  mutate(region = case_when(block_id %in% c("685", "708")~ "Santa Cruz Island",
                            block_id %in% c("653", "652", "666", "665", "684", "664", "683")~ "Santa Barbara",
                            block_id %in% c("702")~"Los Angeles",
                            block_id %in% c("719","718", "740", "739", "738")~"Long Beach",
                            block_id %in% c("756", "802", "801")~"Oceanside", 
                            block_id %in% c("878") ~"San Diego"))

```

```{r}
# save the bycatch data with hotspot block_id above

write.table(distance_bycatch_ratio_block, file = "processed data/distance_bycatch_ratio_block.csv", row.names = F, sep = ",")
```


```{r}
#### Modeling for all data####

distance_bycatch_ratio_block <- read.csv("processed data/distance_bycatch_ratio_block.csv") %>%
  filter(!is.na(region)) %>%
  filter(region != "Santa Cruz Island") %>%
  filter(bycatch_ratio != 0)


# Fit linear regression 
fit_all_lm <- lm(formula = log(bycatch_ratio)~distance_km, data = distance_bycatch_ratio_block)

summary(fit_all_lm)

# Fit to 0.25 quantile
fit_all_0.25 <- rq(formula = log(bycatch_ratio)~distance_km, tau = 0.25, data = distance_bycatch_ratio_block)

summary(fit_all_0.25, se = "nid")

# Fit to 0.5 quantile
fit_all_0.5 <- rq(formula = log(bycatch_ratio)~distance_km, tau = 0.5, data = distance_bycatch_ratio_block)

summary(fit_all_0.5, se = "nid")

# Fit to 0.75 quantile 
fit_all_0.75 <- rq(formula = log(bycatch_ratio)~distance_km, tau = 0.75, data = distance_bycatch_ratio_block)

summary(fit_all_0.75, se = "nid")

#  Fit to 0.9 quantile 
fit_all_0.9 <- rq(formula = log(bycatch_ratio)~distance_km, tau = 0.9, data = distance_bycatch_ratio_block)

summary(fit_all_0.9, se = "nid")

# Fit to 0.95 quantile 
fit_all_0.95 <- rq(formula = log(bycatch_ratio)~distance_km, tau = 0.95, data = distance_bycatch_ratio_block)

summary(fit_all_0.95, se = "nid")
```

```{r}
# Ploting Modeling Result

# Coefs for linear regression 
coefs <- coef(fit_all_lm)
a <- exp(coefs[1])
b <- coefs[2]
x <- seq(0, 10, 0.1)
y <- a*exp(b*x)

#Coefs for 25% quantile regression
coefs_25 <- coef(fit_all_0.25)
a_25 <- exp(coefs_25[1])
b_25 <- coefs_25[2]
y_25 <- a_25*exp(b_25*x)

#Coefs for 50% quantile regression
coefs_50 <- coef(fit_all_0.5)
a_50 <- exp(coefs_50[1])
b_50 <- coefs_50[2]
y_50 <- a_50*exp(b_50*x)

#Coefs for 75% quantile regression
coefs_75 <- coef(fit_all_0.75)
a_75 <- exp(coefs_75[1])
b_75 <- coefs_75[2]
y_75 <- a_75*exp(b_75*x)

# Coefs for 90% quantile regression
coefs_90 <- coef(fit_all_0.9)
a_90 <- exp(coefs_90[1])
b_90 <- coefs_90[2]
y_90 <- a_90*exp(b_90*x)

# Coefs for 95% quantile regression
coefs_95 <- coef(fit_all_0.95)
a_95 <- exp(coefs_95[1])
b_95 <- coefs_95[2]
y_95 <- a_95*exp(b_95*x)


# Build prediction dataframe
pred_df <- tibble(distance_km=x,
                  bycatch_ratio=y,
                  bycatch_ratio_95=y_95,
                  bycatch_ratio_90 = y_90, 
                  bycatch_ratio_75 = y_75,
                  bycatch_ratio_50 = y_50,
                  bycatch_ratio_25 = y_25)

my_theme <-  theme(axis.text=element_text(size=6),
                   axis.title=element_text(size=8),
                   strip.text=element_text(size=7),
                   plot.title=element_blank(),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.background = element_rect(fill=alpha('blue', 0)))

Figure <- ggplot(distance_bycatch_ratio_block, aes(x=distance_km, y=bycatch_ratio)) +
  geom_point(pch=21, color="grey50", alpha=0.5) +
  geom_line(data=pred_df, mapping = aes(x = distance_km, y = bycatch_ratio), linetype = "dashed") +
  geom_line(data=pred_df, mapping=aes(x=distance_km, y=bycatch_ratio_95), color="red") +
  geom_line(data = pred_df, mapping = aes(x = distance_km, y = bycatch_ratio_90), color = "blue") +
  geom_line(data = pred_df, mapping = aes(x = distance_km, y = bycatch_ratio_75), color = "orange") +
  geom_line(data = pred_df, mapping = aes(x = distance_km, y = bycatch_ratio_50), color = "green") +
  geom_line(data = pred_df, mapping = aes(x = distance_km, y = bycatch_ratio_25), color = "purple") +
  scale_y_continuous(lim=c(0,100)) +
  # Labels
  labs(x="Distance to State Water Boundary (km)", y="Bycatch Ratio") +
  # Theme
  theme_bw() + my_theme

Figure

```

```{r}
ggsave(Figure, filename= file.path("Figures", "modeling_fitting_bycatch_ratio_2006-2017.png"),
       width = 7, height = 4, units = "in", dpi = 600)
```

